### ISSUE TITLE
select runs via labels

### ISSUE THREAD

**Issue by PythonFZ** [zincware/paraffin#17]
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-labels-with-self-hosted-runners

and e.g.

```
labels:
  CPU_NODE_1:
    - cpu
  GPU_NODE_1:
    - gpu
  CPU_NODE_2:
    - cpu
```
