### ISSUE TITLE
Error binding parameter 2: type 'list' is not supported

### ISSUE THREAD

**Issue by grst** [zincware/paraffin#51]
Hi Fabian, 

I tried running `paraffin submit` on a project and it fails with

```pytb
ProgrammingError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.ProgrammingError) Error binding parameter 2: type 'list' is not supported
[SQL: INSERT INTO job (name, cmd, status, queue, lock, deps_hash, experiment_id, stderr, stdout, started_at, finished_at, machine, worker, cache) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?) RETURNING id]
[parameters: ('00a_syncdata', ['bash -euo pipefail << EOF\n\nbash src/00_syncdata.sh\n\nEOF\n'], 'cached', 'default', '', '', 1, '', '', None, None, '', '', 1)]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

The corresponding stage looks like this
```yaml
stages:
  00a_syncdata:
    outs:
      - output
    cmd:
      - |
        bash -euo pipefail << EOF

        bash src/00_syncdata.sh

        EOF
    frozen: true
```
